version: '3.9'

services:
  proxy:
    image: nginx-explorer
    pull_policy: never
    container_name: proxy
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/:/var/log/nginx
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - 443:443
      - 8080:8080
      - 8081:8081

