name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
            DATE=$(date +%d%m%y)
            HMS=$(date +%H%M%S)
            echo "DATE: $DATE, HMS: $HMS"
            docker build -t docker.io/atletanetwork/blockscout:${DATE}-${HMS} .
            docker tag docker.io/atletanetwork/blockscout:${DATE}-${HMS} docker.io/atletanetwork/blockscout:latest
            docker push docker.io/atletanetwork/blockscout:${DATE}-${HMS}
            docker push docker.io/atletanetwork/blockscout:latest
          
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.EXPLORER_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)

      - name: Copy Files to Server
        run: |
          scp -r deploy/*    ${{ secrets.HOST_USER}}@${{ secrets.EXPLORER_HOST }}:/blockscout/


      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EXPLORER_HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /blockscout
            docker compose down
            docker compose pull
            docker compose up -d --build --remove-orphans
