name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  sync:
    name: Sync with Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if upstream is set up
        id: check_upstream
        run: |
          UPSTREAM_URL="https://github.com/blockscout/frontend"
          git remote get-url upstream | grep "$UPSTREAM_URL" > /dev/null
          echo "::set-output name=upstream_setup::${PIPESTATUS[1]}"

      - name: Get latest release from upstream
        id: get_latest_release
        if: steps.check_upstream.outputs.upstream_setup == '0'
        run: |
          UPSTREAM_URL="https://github.com/blockscout/frontend"
          UPSTREAM_BRANCH="main"
          LATEST_RELEASE=$(git ls-remote --tags "$UPSTREAM_URL" | awk '{print $2}' | cut -d "/" -f 3 | sort -V | tail -n 1)
          echo "::set-output name=latest_release::$LATEST_RELEASE"

      - name: Check if there's a new release
        id: check_release
        if: steps.check_upstream.outputs.upstream_setup == '0'
        run: |
          LOCAL_BRANCH="atleta"
          UPSTREAM_BRANCH="main"
          if git merge-base --is-ancestor "$LOCAL_BRANCH" "$UPSTREAM_BRANCH"; then
            echo "::set-output name=release_exists::false"
          else
            echo "::set-output name=release_exists::true"
          fi

      - name: Sync with upstream if a new release exists
        id: sync_with_upstream
        if: steps.check_release.outputs.release_exists == 'true' && steps.check_upstream.outputs.upstream_setup == '0'
        run: |
          UPSTREAM_BRANCH="main"
          git fetch upstream "$UPSTREAM_BRANCH"
          git checkout -b sync_branch "upstream/$UPSTREAM_BRANCH"
          git push origin sync_branch

      - name: Create pull request
        if: steps.sync_with_upstream.outputs.success == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync_branch
          commit-message: "Sync with upstream"
          title: "Sync with upstream"
          body: |
            This pull request is automatically generated to sync with the latest changes from the upstream repository.
